# Generated by Django 3.2.5 on 2022-08-29 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('img', models.ImageField(default='', upload_to='pics/')),
                ('area_measure', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('fav_status', models.CharField(default='pending', max_length=100)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestateapp.tb_user')),
            ],
        ),
    ]
