# Generated by Django 3.2.5 on 2022-08-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0002_tb_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_property',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
