# Generated by Django 3.2.5 on 2022-09-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0004_tb_favourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_msg', models.CharField(blank=True, default='', max_length=500)),
                ('reply_msg', models.CharField(blank=True, default='', max_length=500)),
                ('receiver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frds', to='realestateapp.tb_user')),
                ('sender_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestateapp.tb_user')),
            ],
        ),
    ]
