# Generated by Django 3.2.5 on 2022-09-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0005_tb_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('pswd', models.CharField(max_length=100)),
            ],
        ),
    ]
