# Generated by Django 3.2.5 on 2022-09-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0006_tb_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_property',
            name='fav_status',
        ),
    ]
