# Generated by Django 3.2.5 on 2022-09-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0007_remove_tb_property_fav_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_admin',
            name='utype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
