# Generated by Django 3.2.5 on 2022-09-05 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0008_tb_admin_utype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestateapp.tb_user')),
            ],
        ),
    ]
