# Generated by Django 3.2.5 on 2022-09-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0009_tb_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_feedback',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
