# Generated by Django 3.2.5 on 2022-09-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0010_tb_feedback_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_favourites',
            name='area_measure',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tb_favourites',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_favourites',
            name='contact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_favourites',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_favourites',
            name='img',
            field=models.ImageField(default='', upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='tb_favourites',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_favourites',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_favourites',
            name='pro_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
