# Generated by Django 3.2.5 on 2022-09-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0011_auto_20220914_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_property',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
