# Generated by Django 4.1.2 on 2023-02-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0013_tb_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_property',
            name='img1',
            field=models.ImageField(default='', upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='tb_property',
            name='img2',
            field=models.ImageField(default='', upload_to='pics/'),
        ),
    ]
