# Generated by Django 4.1.2 on 2023-04-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0016_tb_property_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_property',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tb_feedback',
            name='feedback',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
